# Generated by Django 3.2.9 on 2022-03-28 01:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipreport',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preference',
            name='finalized',
            field=models.BooleanField(default=False),
        ),
    ]
