# Generated by Django 3.2.9 on 2022-04-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0004_preference_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipreport',
            name='finalized',
            field=models.BooleanField(default=False),
        ),
    ]
