# Generated by Django 3.2.9 on 2022-05-05 12:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0005_internshipreport_finalized'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipreport',
            name='attendance_report_file',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internshipreport',
            name='questionaire_file',
            field=models.FileField(default=None, upload_to=''),
            preserve_default=False,
        ),
    ]
