# Generated by Django 3.2.9 on 2022-03-26 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traineeposition',
            name='finalized',
            field=models.BooleanField(default=False),
        ),
    ]
