# Generated by Django 3.2.9 on 2022-04-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0010_alter_carrierassesement_assesment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='finalized',
            field=models.BooleanField(default=False),
        ),
    ]
