# Generated by Django 3.2.9 on 2022-05-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0012_auto_20220504_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrierassesement',
            name='report_essay_file',
            field=models.FileField(default=None, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicationperiod',
            name='department',
            field=models.CharField(choices=[('IT', 'Informatics and Telematics'), ('G', 'Geogrpaphy'), ('ESD', 'Economics & Sustainable Development'), ('ND', 'Nutrition and  Dietetics'), ('NON', 'Νone')], max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='assignmentperiod',
            name='department',
            field=models.CharField(choices=[('IT', 'Informatics and Telematics'), ('G', 'Geogrpaphy'), ('ESD', 'Economics & Sustainable Development'), ('ND', 'Nutrition and  Dietetics'), ('NON', 'Νone')], max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='carrierassignmentperiod',
            name='department',
            field=models.CharField(choices=[('IT', 'Informatics and Telematics'), ('G', 'Geogrpaphy'), ('ESD', 'Economics & Sustainable Development'), ('ND', 'Nutrition and  Dietetics'), ('NON', 'Νone')], max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='internshipreportperiod',
            name='department',
            field=models.CharField(choices=[('IT', 'Informatics and Telematics'), ('G', 'Geogrpaphy'), ('ESD', 'Economics & Sustainable Development'), ('ND', 'Nutrition and  Dietetics'), ('NON', 'Νone')], max_length=3, unique=True),
        ),
    ]
