# Generated by Django 3.2.9 on 2022-05-05 17:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0013_auto_20220505_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='traineeposition',
            name='supervisor',
            field=models.CharField(default=' ', max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]*$', 'Only alphabetic characters are allowed.')]),
            preserve_default=False,
        ),
    ]
