from django.urls import path
from . import views

app_name = "carrier"
urlpatterns = [
    path(
        "traineepositions/autocomplete",
        views.TraineePositionAutocomplete.as_view(),
        name="traineeposition_autocomple",
    ),
    path(
        "traineepositions/list",
        views.TraineePositionListView.as_view(),
        name="traineeposition_list",
    ),
    path(
        "traineepositions/create",
        views.TraineePositionCreateView.as_view(),
        name="traineeposition_create",
    ),
    path(
        "traineepositions/<int:pk>/view",
        views.TraineePositionDetailView.as_view(),
        name="traineeposition",
    ),
    path(
        "traineepositions/<int:pk>/update",
        views.TraineePositionUpdateView.as_view(),
        name="traineeposition_update",
    ),
    path(
        "traineepositions/<int:pk>/delete",
        views.TraineePositionDeleteView.as_view(),
        name="traineeposition_delete",
    ),
    path(
        "carrier-assignment/not-found",
        views.carrier_assignment_not_found,
        name="carrier_assignment_not_found",
    ),
    path(
        "assignments",
        views.AsssignmentListView.as_view(),
        name="assignments",
    ),
    path(
        "assignments/<int:pk>/detail",
        views.AsssignmentDetailView.as_view(),
        name="assignment_detail",
    ),
    path(
        "assignments/<int:pk>/accept",
        views.assignment_accept,
        name="assignment_accept",
    ),
    path(
        "assignments/<int:pk>/reject",
        views.assignment_reject,
        name="assignment_reject",
    ),
    path(
        "accepted-assignments",
        views.AcceptedAsssignmentListView.as_view(),
        name="accepted_assignments",
    ),
    path(
        "accepted-assignments/<int:pk>/detail",
        views.AcceptedAsssignmentDetailView.as_view(),
        name="accepted_assignment_detail",
    ),
    path(
        "accepted-assignments/<int:pk>/create-assesment",
        views.CarrierAssesementCreateView.as_view(),
        name="create_assesment",
    ),
    path(
        "my-carrier",
        views.CarrierDetailView.as_view(),
        name="carrier_detail",
    ),
    path(
        "my-carrier/update",
        views.CarrierUpdateView.as_view(),
        name="carrier_update",
    ),
]
