# Generated by Django 3.2.9 on 2022-03-23 14:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carrier', '0001_initial'),
        ('internships_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupervisorAssesment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('comments', models.TextField(max_length=1500)),
                ('grade', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('assignement_upon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='carrier.assignment')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internships_app.supervisor')),
            ],
        ),
    ]
