from django.urls import path
from . import views

app_name = "secretary"
urlpatterns = [
    path(
        "students/registrations",
        views.ApprovalRejectionUndergraduateStudentListView.as_view(),
        name="sec_students_registrations",
    ),
    path(
        "students/registrations/<int:pk>/edit",
        views.student_approval_rejection,
        name="sec_students_registrations_edit",
    ),
    path(
        "students/registrations/<int:pk>/activate",
        views.student_approve,
        name="sec_students_registrations_activate",
    ),
    path(
        "students/registrations/<int:pk>/delete",
        views.student_reject,
        name="sec_students_registrations_delete",
    ),
    path(
        "carriers/registrations",
        views.ApprovalRejectionCarrierNodeListView.as_view(),
        name="sec_carriers_registrations",
    ),
    path(
        "carriers/registrations/<int:pk>/edit",
        views.carrier_node_approval_rejection,
        name="sec_carriers_registrations_edit",
    ),
    path(
        "carriers/registrations/<int:pk>/activate",
        views.carrier_node_approve,
        name="carriers_registrations_activate",
    ),
    path(
        "carriers/registrations/<int:pk>/delete",
        views.carrier_node_reject,
        name="carriers_registrations_delete",
    ),
    path(
        "carriers/trainee_positions",
        views.ApprovalTraineePositionsListView.as_view(),
        name="carrier_trainee_positions",
    ),
    path(
        "carriers/trainee_positions/<int:pk>/edit",
        views.trainee_position_approval_rejection,
        name="carrier_trainee_positions_edit",
    ),
    path(
        "carriers/trainee_positions/<int:pk>/update",
        views.SecretaryTraineePositionUpdateView.as_view(),
        name="carrier_trainee_positions_update",
    ),
    path(
        "carriers/trainee_positions/<int:pk>/accept",
        views.trainee_position_approve,
        name="carrier_trainee_positions_accept",
    ),
    path(
        "carriers/trainee_positions/<int:pk>/delete",
        views.SecretaryTraineePositionDeleteView.as_view(),
        name="carrier_trainee_positions_delete",
    ),
    path(
        "students/preferences",
        views.ApprovalPreferencesListView.as_view(),
        name="sec_students_preferences",
    ),
    path(
        "students/preferences/<int:pk>/update",
        views.SecretaryPreferenceUpdateView.as_view(),
        name="students_preferences_update",
    ),
    path(
        "traineepositions/autocomplete",
        views.SecretaryTraineePositionAutocomplete.as_view(),
        name="sec_traineeposition_autocomple",
    ),
    path(
        "students/preferences/<int:pk>/edit",
        views.preference_approval_rejection,
        name="students_preferences_approve",
    ),
    path(
        "students/preferences/<int:pk>/accept",
        views.preferences_approve,
        name="students_preferences_approve",
    ),
    path(
        "students/preferences/<int:pk>/delete",
        views.SecretaryPreferenceDeleteView.as_view(),
        name="students_preferences_delete",
    ),
    path(
        "assignments",
        views.AssingmentListView.as_view(),
        name="sec_assignments",
    ),
    path(
        "assignment",
        views.AssingmentCreateView.as_view(),
        name="sec_assignment_create",
    ),
    path(
        "assignment/<int:pk>/",
        views.AssignmentDetailView.as_view(),
        name="sec_assignment_view",
    ),
    path(
        "assignments/<int:pk>/accept",
        views.assignment_approve,
        name="sec_assignment_approve"
    ),
    path(
        "assignments/<int:pk>/reject",
        views.assignment_reject,
        name="sec_assignment_reject"
    ),
    path(
        "assignments/<int:pk>/finalize",
        views.assignment_finalize,
        name="sec_assignment_finalize"
    ),
    path(
        "assignments/<int:pk>/discard",
        views.assignment_discard,
        name="sec_assignment_dicard"
    ),
    path(
        "assignments/intern_reports/",
        views.InternshipReportListView.as_view(),
        name="sec_assignment_intern_reports"
    ),
    path(
        "assignments/intern_reports/<int:pk>",
        views.InternshipReportDetailView.as_view(),
        name="sec_assignment_intern_report"
    ),
    path(
        "assignments/<int:pk>/intern_report/finalize",
        views.internship_report_finalize,
        name="sec_assignment_intern_report_finalize"
    ),
    path(
        "assignments/intern_reports/<int:pk>/finalize",
        views.internship_report_finalize_basic,
        name="sec_assignment_intern_report_finalize_basic"
    ),
    path(
        "assignments/<int:pk>/intern_report/discard",
        views.internship_report_discard,
        name="sec_assignment_intern_report_discard"
    ),
    path(
        "assignments/intern_reports/<int:pk>/discard",
        views.internship_report_discard_basic,
        name="sec_assignment_intern_report_discard_basic"
    ),
    path(
        "assignments/carrier_assesments/",
        views.CarrierAssesementListView.as_view(),
        name="sec_assignment_carrier_assesements"
    ),
    path(
        "assignments/carrier_assesment/<int:pk>",
        views.CarrierAssesementDetailView.as_view(),
        name="sec_assignment_carrier_assesement"
    ),
    path(
        "assignments/carrier_assesment/<int:pk>/finalize",
        views.carrier_assesment_finalize_basic,
        name="sec_assignment_carrier_assesement_finalize_basic"
    ),
    path(
        "assignments/<int:pk>/carrier_assesment/finalize",
        views.carrier_assesment_finalize,
        name="sec_assignment_carrier_assesement_finalize"
    ),
    path(
        "assignments/carrier_assesment/<int:pk>/discard",
        views.carrier_assesment_discard,
        name="sec_assignment_carrier_assesement_discard"
    ),
    path(
        "assignments/carrier_assesments/<int:pk>/discard",
        views.carrier_assesment_discard_basic,
        name="sec_assignment_carrier_assesement_discard_basic"
    ),
    path(
        "assignments/supervisor_assesments/",
        views.SupervisorAssesmentListView.as_view(),
        name="sec_assignment_supervisor_assesements"
    ),
    path(
        "assignments/supervisor_assesment/<int:pk>",
        views.SupervisorAssesmentDetailView.as_view(),
        name="sec_assignment_supervisor_assesement"
    ),
    path(
        "assignments/<int:pk>/supervisor_assesment/finalize",
        views.supervisor_assesment_finalize,
        name="sec_assignment_supervisor_assesement_finalize"
    ),
    path(
        "assignments/supervisor_assesment/<int:pk>/finalize",
        views.supervisor_assesment_finalize_basic,
        name="sec_assignment_supervisor_assesement_finalize"
    ),
    path(
        "assignments/<int:pk>/supervisor_assesment/discard",
        views.supervisor_assesment_discard,
        name="sec_assignment_supervisor_assesement_discard"
    ),
    path(
        "assignments/supervisor_assesment/<int:pk>/discard",
        views.supervisor_assesment_discard_basic,
        name="sec_assignment_supervisor_assesement_discard"
    ),
]
